name: tot_pos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # state managment
  bloc:
  bloc_provider:
  flutter_bloc:

  intl:
  flutter_slidable: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image:
  # Api
  dio: ^5.3.2
  # charts
  fl_chart: ^0.63.0
  # routing
  go_router:
    # local database
  shared_preferences: ^2.2.0
  # responsive
  flutter_screenutil: ^5.9.0
  # freezed
  freezed_annotation:
  json_annotation:
  # injection
  get_it: ^7.6.0
  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter-atoms.git
      path: packages/tot_atomic_design
      ref: dev

dev_dependencies:
  build_runner:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:

dependency_overrides:
  intl:

flutter:
  uses-material-design: true
  assets:
    - assets/
