name: tot_pos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.5
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  custom_keyboard: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^13.0.1
  graphql_flutter: ^5.1.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter.git
      path: packages/atomic_design
      ref: beta
  mocktail:
  equatable: ^2.0.5
  fl_chart: ^0.65.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
#  feature/login
#   ? intl
#  feature/demo
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    # - assets/fonts/
    # - assets/icons/global/
    - assets/icons/
    # - assets/svg/
    - assets/jsons/
# - assets/configuration/app_configuration.json
