name: tot_pos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.5
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  custom_keyboard: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.4
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  fl_chart: ^0.65.0
  fluentui_system_icons: ^1.1.222
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  graphql_flutter: ^5.1.2
  image_picker: ^1.0.4
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  mockito: ^5.4.3
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  # internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.1.0

  # tot_atomic_design:
  #   git:
  #     url: https://github.com/TOTPLATFORM/flutter.git
  #     path: packages/atomic_design
  #     ref: tablet-beta
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter.git
      path: packages/atomic_design
      ref: tablet-beta
  url_launcher: ^6.2.1
  wakelock_plus: ^1.1.3

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

dependency_overrides:

#  feature/login
#   ? intl
#  feature/demo


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    # - assets/fonts/
    # - assets/icons/global/
    # - assets/icons/
    # - assets/svg/
    - assets/jsons/
    # - assets/configuration/app_configuration.json
