name: tot_pos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  firebase_messaging: ^14.7.5

  logger: ^2.0.2+1

  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  go_router: ^12.1.1

  flutter_staggered_animations: ^1.1.1

  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI
  fluentui_system_icons: ^1.1.222

  intl: ^0.18.1
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  flutter_remix: ^0.0.3
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.5.0
  dio: ^5.3.4
  equatable: ^2.0.5
  shimmer: ^3.0.0
  mockito: ^5.4.3
  bloc_test: ^9.1.5
  graphql_flutter: ^5.1.2
  wakelock_plus: ^1.1.3
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  # internet_connection_checker: ^1.0.0+1
  internet_connection_checker_plus: ^2.1.0

  # tot_atomic_design:
  #   git:
  #     url: https://github.com/TOTPLATFORM/flutter.git
  #     path: packages/atomic_design
  #     ref: tablet-beta

  tot_atomic_design:
    path: flutter/packages/atomic_design
  flutter_slidable: ^3.0.1
  custom_keyboard: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

dependency_overrides:
  
  intl:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    # - assets/fonts/
    # - assets/icons/global/
    # - assets/icons/
    # - assets/svg/
    - assets/jsons/
    # - assets/configuration/app_configuration.json
