name: tot_pos
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  bloc:
  flutter_bloc:
  freezed_annotation:
  intl:
  tot_atomic_design:
    git:
      url: https://github.com/TOTPLATFORM/flutter-atoms.git
      path: packages/tot_atomic_design
      ref: dev

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed:

dependency_overrides:
  intl:

flutter:
  uses-material-design: true
  assets:
    - assets/
